# Generated by Django 4.0.6 on 2022-07-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_alter_board_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': '게시판', 'verbose_name_plural': '게시판'},
        ),
        migrations.RemoveField(
            model_name='board',
            name='slug',
        ),
    ]
