# Generated by Django 4.0.6 on 2022-07-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_alter_board_options_remove_board_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': '작성자', 'verbose_name_plural': '작성자'},
        ),
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
    ]
